const normalizeNameMap = {
    "AR Lit Rock": "Little Rock",
    "Abl Christian": "Abilene Christian",
    "Alcorn St Braves": "Alcorn State",
    "Alab A&M": "Alabama A&M",
    American: "American University",
    "Alabama St": "Alabama State",
    "Arizona St": "Arizona State",
    "Arizona St Sun Devils": "Arizona State",
    "Arizona Wildcats": "Arizona",
    "Auburn Tigers": "Auburn",
    "Arkansas Razorbacks": "Arkansas",
    "Baylor Bears": "Baylor",
    "Boise State Broncos": "Boise State",
    "Arkansas St": "Arkansas State",
    "App State": "Appalachian State",
    "Ark Pine Bl": "Arkansas-Pine Bluff",
    Army: "Army West Point",
    "Boston U": "Boston University",
    "Boston Col": "Boston College",
    "Bowling Grn": "Bowling Green",
    "CS Bakersfld": "Cal State Bakersfield",
    "Cal Baptist": "California Baptist",
    "Cal St Nrdge": "Cal State Northridge",
    "Central Ark": "Central Arkansas",
    "Central Conn": "Central Connecticut State",
    "Central Mich": "Central Michigan",
    "Charl South": "Charleston Southern",
    "Cleveland St": "Cleveland State",
    "Coastal Car": "Coastal Carolina",
    "Colorado St": "Colorado State",
    Detroit: "Detroit Mercy",
    "E Illinois": "Eastern Illinois",
    "E Michigan": "Eastern Illinois",
    "E Tenn St": "East Tennessee State",
    "F Dickinson": "Fairleigh Dickinson",
    "Fla Gulf Cst": "Florida Gulf Coast",
    "Florida Intl": "Florida International",
    "Florida St": "Florida State",
    "Fresno St": "Fresno State",
    "Wm & Mary": "William & Mary",
    "Wash State": "Washington State",
    "WI-Grn Bay": "Green Bay",
    "W Virginia": "West Virginia",
    "W Michigan": "Western Michigan",
    "W Kentucky": "Western Kentucky",
    "VA Tech": "Virginia Tech",
    "VA Military": "Virginia Military",
    "U Mass": "UMass Lowell",
    "TX-San Ant": "Texas-San Antonio",
    "TX-Arlington": "Texas-Arlington",
    "TX Southern": "Texas Southern",
    "TX Christian": "Texas Christian",
    "TX A&M-Com": "Texas A&M Commerce",
    "TN State": "Tennessee State",
    "TN Martin": "Tennessee-Martin",
    "St Peters": "Saint Peter's",
    "St Johns": "St. John's",
    "St Fran (PA)": "St. Francis (PA)",
    "San Diego St": "San Diego State",
    "Sacred Hrt": "Sacred Heart",
    "Florida St": "Florida State",
    "Gard-Webb": "Gardner-Webb",
    "Geo Wshgtn": "George Washington",
    "Georgia St": "Georgia State",
    "Grd Canyon": "Grand Canyon",
    "Hsn Christian": "Houston Christian",
    IPFW: "Fort Wayne", // unsure
    "Illinois St": "Illinois State",
    "LA Monroe": "Louisiana-Monroe",
    "LA Tech": "Louisiana Tech",
    LIU: "Long Island",
    "Lg Beach St": "Long Beach State",
    "Loyola-Chi": "Loyola (IL)",
    "Loyola-MD": "Loyola (MD)",
    "Maryland BC": "Maryland", // unsure
    "McNeese St": "McNeese State",
    Merrimack: "Merrimack College",
    "Michigan St": "Michigan State",
    "Miss State": "Mississippi State",
    Mississippi: "Southern Mississippi", // unsure
    "Missouri St": "Missouri State",
    "Morgan St": "Morgan State",
    "Mt St Marys": "Mount St. Mary's",
    "Murray St": "Murray State",
    "N Carolina": "North Carolina",
    "N Colorado": "Northern Colorado",
    "N Dakota St": "North Dakota State",
    "N Hampshire": "New Hampshire",
    "N Iowa": "Northern Iowa",
    "N Kentucky": "Northern Kentucky",
    "N Mex State": "New Mexico State",
    "NC A&T": "North Carolina A&T",
    "NC-Grnsboro": "UNC Greensboro",
    "Nicholls St": "Nicholls State",
    Northeastrn: "Northeastern",
    "Oklahoma St": "Oklahoma State",
    "Oregon St": "Oregon State",
    "Portland St": "Portland State",
    "Prairie View": "Prairie View A&M",
    "S Car State": "South Carolina State",
    "S Dakota St": "South Dakota State",
    "S Illinois": "Southern Illinois",
    "S Indiana": "Southern Indiana",
    "S Methodist": "Southern Methodist",
    "SIU Edward": "SIU-Edwardsville",
    "Sac State": "Sacramento State",
    "Loyola Mymt": "Loyola Marymount",
    "SE Missouri": "Southeast Missouri State",
    "SE Missouri St Redhawks": "Southeast Missouri State",
    "TX A&M-CC": "Texas A&M-CC",
    "Texas A&M-CC Islanders": "Texas A&M-CC",
    "Bradley Braves": "Bradley",
    "Charleston Cougars": "Charleston",
    "Charlotte 49ers": "Charlotte",
    "Cincinnati Bearcats": "Cincinnati",
    "Clemson Tigers": "Clemson",
    "Cleveland St Vikings": "Cleveland State",
    "Colgate Raiders": "Colgate",
    "Colorado Buffaloes": "Colorado",
    "UConn Huskies": "Connecticut",
    "Creighton Bluejays": "Creighton",
    "Drake Bulldogs": "Drake",
    "Duke Blue Devils": "Duke",
    "Duquesne Dukes": "Duquesne",
    "Eastern Kentucky Colonels": "Eastern Kentucky",
    "Eastern Washington Eagles": "Eastern Washington",
    "Fairleigh Dickinson Knights": "Fairleigh Dickinson",
    "Florida Gators": "Florida",
    "Florida Atlantic Owls": "Florida Atlantic",
    "Furman Paladins": "Furman",
    "Gonzaga Bulldogs": "Gonzaga",
    "Grand Canyon Antelopes": "Grand Canyon",
    "Hofstra Pride": "Hofstra",
    "Houston Cougars": "Houston",
    "Howard Bison": "Howard",
    "Illinois Fighting Illini": "Illinois",
    "Indiana Hoosiers": "Indiana",
    "Indiana St Sycamores": "Indiana St",
    "Iona Gaels": "Iona",
    "Iowa Hawkeyes": "Iowa",
    "Kansas Jayhawks": "Kansas",
    "Kansas St Wildcats": "Kansas State",
    "Kansas St": "Kansas State",
    "Kennesaw St Owls": "Kennesaw State",
    "Kennesaw St": "Kennesaw State",
    "Kent State Golden Flashes": "Kent State",
    "Kentucky Wildcats": "Kentucky",
    "Liberty Flames": "Liberty",
    "Louisiana Ragin' Cajuns": "Louisiana",
    "Marquette Golden Eagles": "Marquette",
    "Maryland Terrapins": "Maryland",
    "Maryland ES": "Maryland-Eastern Shore",
    "Memphis Tigers": "Memphis",
    "Miami Hurricanes": "Miami (FL)",
    "Michigan Wolverines": "Michigan",
    "Michigan St Spartans": "Michigan State",
    "Milwaukee Panthers": "Milwaukee",
    "Mississippi St Bulldogs": "Mississippi State",
    "Miss Val St": "Mississippi Valley State",
    "Missouri Tigers": "Missouri",
    "Montana St Bobcats": "Montana State",
    "Montana St": "Montana State",
    "Morehead St Eagles": "Morehead State",
    "Morehead St": "Morehead State",
    "NC State Wolfpack": "NC State",
    "UNC Asheville Bulldogs": "NC-Asheville",
    "Nevada Wolf Pack": "Nevada",
    "New Mexico Lobos": "New Mexico",
    "North Alabama Lions": "North Alabama",
    "North Texas Mean Green": "North Florida",
    "Northern Kentucky Norse": "Northern Kentucky",
    "Northwestern Wildcats": "Northwestern",
    "Oklahoma St Cowboys": "Oklahoma State",
    "Oral Roberts Golden Eagles": "Oral Roberts",
    "Oregon Ducks": "Oregon",
    "Penn State Nittany Lions": "Penn State",
    "Pittsburgh Panthers": "Pittsburgh",
    "Princeton Tigers": "Princeton",
    "Providence Friars": "Providence",
    "Radford Highlanders": "Radford",
    "Rice Owls": "Rice",
    "Rutgers Scarlet Knights": "Rutgers",
    "Saint Mary's Gaels": "Saint Mary's",
    "Sam Hous St": "Sam Houston State",
    "Sam Houston St Bearkats": "Sam Houston State",
    "San Diego St Aztecs": "San Diego State",
    "San Jose St": "San Jose State",
    "San José St Spartans": "San Jose State",
    "Santa Clara Broncos": "Santa Clara",
    "Seton Hall Pirates": "Seton Hall",
    "SE Missouri St Redhawks": "Southeast Missouri State",
    "Southern Indiana Screaming Eagles": "Southern Indiana",
    "Southern Miss Golden Eagles": "Southern Mississippi",
    "Southern Utah Thunderbirds": "Southern Utah",
    "Stetson Hatters": "Stetson",
    "Tarleton State Texans": "Tarleton State",
    "Tennessee Volunteers": "Tennessee",
    "Texas Longhorns": "Texas",
    "Texas A&M Aggies": "Texas A&M",
    "Texas A&M-CC Islanders": "Texas A&M-CC",
    "Texas Southern Tigers": "Texas Southern",
    "UAB Blazers": "UAB",
    "UC Irvine Anteaters": "UC Irvine",
    "UC Santa Barbara Gauchos": "UC Santa Barbara",
    "UCF Knights": "UCF",
    "UCLA Bruins": "UCLA",
    "USC Trojans": "USC",
    "South Carolina Upstate Spartans": "USC Upstate",
    "Utah State Aggies": "Utah State",
    "Utah Valley Wolverines": "Utah Valley",
    "VCU Rams": "VCU",
    "Vanderbilt Commodores": "Vanderbilt",
    "Vermont Catamounts": "Vermont",
    "Villanova Wildcats": "Villanova",
    "Virginia Cavaliers": "Virginia",
    "Virginia Tech Hokies": "Virginia Tech",
    "Washington St Cougars": "Washington State",
    "West Virginia Mountaineers": "West Virginia",
    "Western Carolina Catamounts": "Western Carolina",
    "Wisconsin Badgers": "Wisconsin",
    "Xavier Musketeers": "Xavier",
    "Yale Bulldogs": "Yale",
    "Youngs St": "Youngstown State",
    "Youngstown St Penguins": "Youngstown State",
    "Beth-Cook": "Bethune-Cookman",
    "CS Fullerton": "Cal State Fullerton",
    "Fla Atlantic": "Florida Atlantic",
    "Chicago St": "Chicago State",
    "Delaware St": "Delaware State",
    "Detroit-Mercy": "Detroit Mercy",
    "E Carolina": "East Carolina",
    "E Kentucky": "Eastern Kentucky",
    "E Washingtn": "Eastern Washington",
    "Geo Mason": "George Mason",
    "Grambling St": "Grambling State",
    "GA Southern": "Georgia Southern",
    "GA Tech": "Georgia Tech",
    "IL-Chicago": "Illinois-Chicago",
    "Incar Word": "Incarnate Word",
    "Jackson St": "Jackson State",
    "James Mad": "James Madison",
    "Jksnville St": "Jacksonville State",
    "LA Lafayette": "Lafayette",
    "Middle Tenn": "Middle Tennessee State",
    "N Alabama": "North Alabama",
    "N Florida": "North Florida",
    "N Illinois": "Northern Illinois",
    "N Arizona": "Northern Arizona",
    NJIT: "N.J.I.T.",
    "NC Central": "North Carolina Central",
    "NC-Asheville": "UNC Asheville",
    "NC-Wilmgton": "UNC Wilmington",
    "S Alabama": "South Alabama",
    "S Carolina": "South Carolina",
    "S Florida": "South Florida",
    "SE Louisiana": "Southeastern Louisiana",
    "S Mississippi": "Southern Mississippi",
    "S Utah": "Southern Utah",
    "St Fran (NY)": "St. Francis (NY)",
    "San Diego": "UC San Diego",
    "SC Upstate": "USC Upstate",
    "NW State": "Northwestern State",
    "Neb Omaha": "Omaha",
    Queens: "Queens University",
    "Rob Morris": "Robert Morris",
    "Wichita St": "Wichita State",
    "Indiana St": "Indiana State",
    "Jackson State": "Jacksonville State",
    "U Penn": "Pennsylvania",
    "St Josephs": "Saint Joseph's",
    "St Marys": "Saint Mary's",
    UCSB: "UC Santa Barbara",
    "W Carolina": "Western Carolina",
    "W Illinois": "Western Illinois",
}

function normalizeTeamName(teamName) {
    const startingParen = teamName.lastIndexOf("(")
    if (
        startingParen !== -1 &&
        startingParen > 0 &&
        teamName[startingParen - 1] !== " "
    ) {
        teamName = teamName.slice(0, startingParen)
    }
    if (teamName in normalizeNameMap) {
        return normalizeNameMap[teamName]
    }
    return teamName
}

exports.normalizeTeamName = normalizeTeamName
